name = "sp2yt"
main = "src/worker.ts"
compatibility_date = "2026-08-25"
workers_dev = true

routes = [
  { pattern = "sp2yt.coding-global.com", custom_domain = true }
]

[assets]
directory = "./public"

[observability]
enabled = true

[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 20, period = 60 }
